/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import sdapkg.Team;

/**
 *
 * @author mixalis
 */
public class TeamStats extends javax.swing.JFrame {

    /**
     * Creates new form TeamStats
     */
    public TeamStats(Team team) {
        initComponents();
        this.setTitle(team.getNameInSite1());
       
        String[] Pr=team.getProp().split(",");

        this.jLabel4.setText(Pr[0]);
        this.jLabel1.setText(Pr[1]);
        this.jLabel6.setText(Pr[2]);
        
        String[] seq=team.getSeq().split(" ");
        
        this.jLabel14.setText(seq[0]);
        this.jLabel7.setText(seq[1]);
        this.jLabel12.setText(seq[2]);
        this.jLabel13.setText(seq[3]);
        this.jLabel16.setText(seq[4]);
        this.jLabel18.setText(seq[5]);
        
       
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setBounds(new java.awt.Rectangle(10, 10, 10, 10));
        setMinimumSize(new java.awt.Dimension(400, 250));
        getContentPane().setLayout(new java.awt.GridLayout(4, 0, 10, 10));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 10, 5));

        jLabel3.setText("Winning Propability");
        jPanel1.add(jLabel3);

        jLabel2.setText("Draw Propability");
        jPanel1.add(jLabel2);

        jLabel5.setText("Losing Propability");
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 8, 8));

        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);

        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6);

        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 6));

        jLabel9.setBackground(new java.awt.Color(153, 204, 255));
        jLabel9.setText("Winning ");
        jPanel3.add(jLabel9);

        jLabel8.setBackground(new java.awt.Color(153, 204, 255));
        jLabel8.setText("Winless");
        jPanel3.add(jLabel8);

        jLabel11.setBackground(new java.awt.Color(153, 204, 255));
        jLabel11.setText("Drawing");
        jPanel3.add(jLabel11);

        jLabel10.setBackground(new java.awt.Color(153, 204, 255));
        jLabel10.setText("Not Draw");
        jPanel3.add(jLabel10);

        jLabel15.setBackground(new java.awt.Color(153, 204, 255));
        jLabel15.setText("Losing");
        jPanel3.add(jLabel15);

        jLabel17.setBackground(new java.awt.Color(153, 204, 255));
        jLabel17.setText("Unbeaten");
        jPanel3.add(jLabel17);

        getContentPane().add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 6));

        jLabel14.setText("jLabel14");
        jPanel4.add(jLabel14);

        jLabel7.setText("jLabel7");
        jPanel4.add(jLabel7);

        jLabel12.setText("jLabel12");
        jPanel4.add(jLabel12);

        jLabel13.setText("jLabel13");
        jPanel4.add(jLabel13);

        jLabel16.setText("jLabel16");
        jPanel4.add(jLabel16);

        jLabel18.setText("jLabel18");
        jPanel4.add(jLabel18);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
